server:
  port: 8081
  servlet:
    context-path: /mobile-app

spring:
  jpa.hibernate.ddl-auto: update
  # settings for MYSQL DB
  datasource:
    url: jdbc:mysql://localhost:3306/photo_app?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: iggy
    password: Kling#123
# settings for H2 in memory DB
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#    database-platform: org.hibernate.dialect.H2Dialect
#  h2.console.enabled: true


token-secret: "jf9i4jgu83nfl0"